version: '3.1'

services:
  nginx:
    build: ./nginx
    ports:
      - 80:80

  nextjs:
    build: ./
    environment:
      DATABASE_URL: postgresql://postgres:example@postgres:5432/postgres?schema=public
      REDIS_URL: redis:6379
    ports:
      - 3000:3000

  postgres:
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: example
    ports:
      - 5432:5432

  redis:
    image: redis
    restart: always
    ports:
      - 6379:6379

  adminer:
    image: adminer
    restart: always
    ports:
      - 8081:8080
