version: "3.1"

include:
  - ./services/authentication/docker-compose.yaml
  - ./services/authorization/docker-compose.yaml

services:
  adminer:
    image: adminer
    restart: always
    ports:
      - 8081:8080
