packages:
  - "apps/backend"
  - "apps/frontend"
  - "migrations/monolith-to-modules"
  - "packages/custom-error"
  - "packages/eslint-config"
  - "packages/eslint-plugin-returned-errors"
  - "packages/fetch-retry"
  - "packages/hono-utils"
  - "services/authentication"
  - "services/authorization"
  - "services/genres"
  - "services/media"
  - "services/user-settings"
