packages:
  - "apps/frontend"
  - "apps/backend"
  - "packages/authentication"
  - "packages/authorization"
  - "packages/eslint-config"
  - "packages/eslint-plugin-returned-errors"
  - "packages/media"
