packages:
  - "apps/frontend"
  - "apps/backend"
  - "packages/eslint-config"
  - "packages/eslint-plugin-returned-errors"
  - "services/authentication"
  - "services/authorization"
  - "services/genres"
  - "services/media"
  - "services/user-settings"
