services:
  postgres:
    image: postgres
    volumes:
      - ./volume:/docker-entrypoint-initdb.d
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_MULTIPLE_DATABASES: authn,authz,genres,user_settings,media
    command:
      [
        "postgres",
        "-c",
        "log_statement=all",
        "-c",
        "log_destination=stderr",
        "-c",
        "logging_collector=off",
        "-c",
        "log_min_duration_statement=0",
      ]
    ports:
      - 5432:5432

  adminer:
    image: adminer
    ports:
      - 8081:8080
