on:
  workflow_call:
    secrets:
      AWS_ACCOUNT_ID:
        required: true
    outputs:
      frontend_image_tag:
        description: "The tag for the frontend image"
        value: ${{ jobs.frontend.outputs.frontend_image_tag }}
      backend_image_tag:
        description: "The tag for the backend image"
        value: ${{ jobs.backend.outputs.backend_image_tag }}

jobs:
  frontend:
    runs-on: ubuntu-latest
    outputs:
      frontend_image_tag: ${{ steps.tags.outputs.version_tag }}
    permissions:
      id-token: write
      contents: read
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Generate image tags
        id: tags
        run: |
          VERSION_TAG=$(date +%Y%m%d%H%M%S)-${GITHUB_SHA::8}
          echo "version_tag=$VERSION_TAG" >> $GITHUB_OUTPUT

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::${{ secrets.AWS_ACCOUNT_ID }}:role/github-actions-role
          aws-region: us-east-2

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v2
        with:
          registries: ${{ secrets.AWS_ACCOUNT_ID }}

      - name: Build and push frontend image
        uses: docker/build-push-action@v5
        with:
          context: .
          file: apps/frontend/Dockerfile
          push: true
          tags: ${{ steps.login-ecr.outputs.registry }}/frontend:${{ steps.tags.outputs.version_tag }}

  backend:
    runs-on: ubuntu-latest
    outputs:
      backend_image_tag: ${{ steps.tags.outputs.version_tag }}
    permissions:
      id-token: write
      contents: read
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Generate image tags
        id: tags
        run: |
          VERSION_TAG=$(date +%Y%m%d%H%M%S)-${GITHUB_SHA::8}
          echo "version_tag=$VERSION_TAG" >> $GITHUB_OUTPUT

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::${{ secrets.AWS_ACCOUNT_ID }}:role/github-actions-role
          aws-region: us-east-2

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v2
        with:
          registries: ${{ secrets.AWS_ACCOUNT_ID }}

      - name: Build and push backend image
        uses: docker/build-push-action@v5
        with:
          context: .
          file: apps/backend/Dockerfile
          push: true
          tags: ${{ steps.login-ecr.outputs.registry }}/backend:${{ steps.tags.outputs.version_tag }}
