name: Deploy

on:
  workflow_call:
    inputs:
      frontend_image_tag:
        required: true
        type: string
        description: "The tag for the frontend image"
      backend_image_tag:
        required: true
        type: string
        description: "The tag for the backend image"
    secrets:
      AWS_ACCOUNT_ID:
        required: true

env:
  NODE_VERSION: 20.x
  TERRAFORM_DIR: iac/application

jobs:
  deploy:
    runs-on: ubuntu-latest

    permissions:
      id-token: write
      contents: read

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::${{ secrets.AWS_ACCOUNT_ID }}:role/github-actions-role
          aws-region: us-east-2

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_wrapper: false

      - name: Terraform Init
        working-directory: ${{ env.TERRAFORM_DIR }}
        run: terraform init

      - name: Apply Terraform with new image tags
        working-directory: ${{ env.TERRAFORM_DIR }}
        run: |
          terraform apply -auto-approve \
            -var="frontend_image_tag=${{ inputs.frontend_image_tag }}" \
            -var="backend_image_tag=${{ inputs.backend_image_tag }}" \
            -var="allowed_ssh_ip=${{ secrets.ALLOWED_SSH_IP }}" \
            -var="bastion_public_key=${{ secrets.BASTION_PUBLIC_KEY }}"
