name: Push

on:
  push:
    branches:
      - main

env:
  NODE_VERSION: 20.x

jobs:
  validation:
    uses: ./.github/workflows/validation.yaml

  build:
    needs: [validation]
    uses: ./.github/workflows/build.yaml
    secrets:
      AWS_ACCOUNT_ID: ${{ secrets.AWS_ACCOUNT_ID }}

  deploy:
    needs: [build]
    uses: ./.github/workflows/deploy.yaml
    secrets:
      AWS_ACCOUNT_ID: ${{ secrets.AWS_ACCOUNT_ID }}
    with:
      frontend_image_tag: ${{ needs.build.outputs.frontend_image_tag }}
      backend_image_tag: ${{ needs.build.outputs.backend_image_tag }}
