name: Push

on:
  push:
    branches:
      - main

env:
  NODE_VERSION: 20.x

jobs:
  validation:
    uses: ./.github/workflows/validation.yaml

  build:
    needs: [validation]
    uses: ./.github/workflows/build.yaml
    secrets:
      AWS_ACCOUNT_ID: ${{ secrets.AWS_ACCOUNT_ID }}
