name: Push

on:
  push:
    branches:
      - main

env:
  NODE_VERSION: 20.x

jobs:
  validation:
    uses: ./.github/workflows/validation.yaml

  build:
    needs: [validation]
    uses: ./.github/workflows/build.yaml
    secrets:
      AWS_ACCOUNT_ID: ${{ secrets.AWS_ACCOUNT_ID }}

  deploy:
    needs: [build]
    uses: ./.github/workflows/deploy.yaml
    secrets:
      AWS_ACCOUNT_ID: ${{ secrets.AWS_ACCOUNT_ID }}
      ALLOWED_SSH_IP: ${{ secrets.ALLOWED_SSH_IP }}
      BASTION_PUBLIC_KEY: ${{ secrets.BASTION_PUBLIC_KEY }}
      CLOUDFLARE_ZONE_ID: ${{ secrets.CLOUDFLARE_ZONE_ID }}
      CLOUDFLARE_API_TOKEN: ${{ secrets.CLOUDFLARE_API_TOKEN }}
    with:
      frontend_image_tag: ${{ needs.build.outputs.frontend_image_tag }}
      backend_image_tag: ${{ needs.build.outputs.backend_image_tag }}
